"""
Deadline-aware prep scheduling.

Will allocate available prep hours (from interview date and hours
available per day) across prioritized skills using deterministic Python
logic. Actual study-task wording is generated by the LLM only after
this time allocation has already been computed.
"""
