-- RoleRadar PostgreSQL schema (Supabase)
--
-- Run this file once against a fresh Supabase project via the SQL Editor
-- (see README.md for the exact steps). It is written to be re-runnable:
-- CREATE TABLE IF NOT EXISTS guards are used so it does not fail on a
-- second run, but it will NOT migrate an already-diverged schema. For
-- real migrations, use a proper migration tool later.
--
-- ID strategy: every table uses a UUID primary key generated by
-- gen_random_uuid() (pgcrypto, enabled by default on Supabase). Business
-- keys (external_id, normalized_skill_name, etc.) carry the uniqueness
-- constraints that make ingestion idempotent - see backend/db/upserts.py.
--
-- Auth: authentication is intentionally NOT implemented yet. The `users`
-- table is a minimal placeholder for a single development/demo user so
-- every other table can carry a real user_id foreign key from day one.
-- Swapping in Supabase Auth later only means pointing user_id at
-- auth.users instead of this table.

create extension if not exists pgcrypto;

-- ---------------------------------------------------------------------
-- users
-- ---------------------------------------------------------------------
create table if not exists users (
    id uuid primary key default gen_random_uuid(),
    email text not null unique,
    display_name text,
    created_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------
-- candidate_profiles
-- One structured profile per user, built from parsed resume(s).
-- ---------------------------------------------------------------------
create table if not exists candidate_profiles (
    id uuid primary key default gen_random_uuid(),
    user_id uuid not null references users(id) on delete cascade,
    raw_resume_text text,
    education jsonb not null default '[]'::jsonb,
    experience jsonb not null default '[]'::jsonb,
    projects jsonb not null default '[]'::jsonb,
    interests jsonb not null default '[]'::jsonb,
    constraints jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (user_id)
);

-- ---------------------------------------------------------------------
-- candidate_skills
-- Per-user normalized skill estimates with confidence.
-- ---------------------------------------------------------------------
create table if not exists candidate_skills (
    id uuid primary key default gen_random_uuid(),
    user_id uuid not null references users(id) on delete cascade,
    normalized_skill_name text not null,
    display_name text,
    estimated_level numeric(4, 2) not null default 0,
    confidence numeric(4, 2) not null default 0,
    evidence_source text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (user_id, normalized_skill_name)
);

-- ---------------------------------------------------------------------
-- roles
-- Ingested job postings, deduplicated on external_id.
-- ---------------------------------------------------------------------
create table if not exists roles (
    id uuid primary key default gen_random_uuid(),
    external_id text not null,
    company text not null,
    title text not null,
    location text,
    url text,
    description text,
    role_family text,
    raw_source jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (external_id)
);

-- ---------------------------------------------------------------------
-- role_requirements
-- Structured requirements extracted per role. A given skill can only
-- appear once per role.
-- ---------------------------------------------------------------------
create table if not exists role_requirements (
    id uuid primary key default gen_random_uuid(),
    role_id uuid not null references roles(id) on delete cascade,
    normalized_skill_name text not null,
    display_name text,
    target_level numeric(4, 2) not null default 0,
    importance numeric(4, 2) not null default 1,
    is_required boolean not null default true,
    evidence jsonb not null default '[]'::jsonb,
    created_at timestamptz not null default now(),
    unique (role_id, normalized_skill_name)
);

-- Safe to re-run against a database created from an earlier version of
-- this schema, before requirement evidence was persisted
-- (backend.llm.extract_requirements.RoleRequirement.evidence).
alter table role_requirements add column if not exists evidence jsonb not null default '[]'::jsonb;

-- ---------------------------------------------------------------------
-- fit_scores
-- One deterministic overall fit score per (user, role).
-- ---------------------------------------------------------------------
create table if not exists fit_scores (
    id uuid primary key default gen_random_uuid(),
    user_id uuid not null references users(id) on delete cascade,
    role_id uuid not null references roles(id) on delete cascade,
    overall_score numeric(5, 2) not null,
    weights_used jsonb not null default '{}'::jsonb,
    computed_at timestamptz not null default now(),
    unique (user_id, role_id)
);

-- ---------------------------------------------------------------------
-- score_components
-- Breakdown of a fit score into named components (technical, experience,
-- coursework, domain, interest, constraints, ...).
-- ---------------------------------------------------------------------
create table if not exists score_components (
    id uuid primary key default gen_random_uuid(),
    fit_score_id uuid not null references fit_scores(id) on delete cascade,
    component_name text not null,
    component_value numeric(5, 2) not null,
    weight numeric(4, 2) not null,
    created_at timestamptz not null default now(),
    unique (fit_score_id, component_name)
);

-- ---------------------------------------------------------------------
-- favorites
-- User-flagged saved roles. Persistent, not Streamlit session state.
-- ---------------------------------------------------------------------
create table if not exists favorites (
    id uuid primary key default gen_random_uuid(),
    user_id uuid not null references users(id) on delete cascade,
    role_id uuid not null references roles(id) on delete cascade,
    priority text not null default 'interested'
        check (priority in ('dream', 'high', 'interested', 'backup')),
    notes text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (user_id, role_id)
);

-- Safe to re-run against a database created from an earlier version of
-- this schema, before priority/notes/updated_at existed on favorites.
alter table favorites add column if not exists priority text not null default 'interested';
alter table favorites add column if not exists notes text;
alter table favorites add column if not exists updated_at timestamptz not null default now();
alter table favorites drop constraint if exists favorites_priority_check;
alter table favorites add constraint favorites_priority_check
    check (priority in ('dream', 'high', 'interested', 'backup'));

-- ---------------------------------------------------------------------
-- applications
-- Pipeline status per (user, role): discovered -> saved -> applied -> oa
-- -> interview -> offer / rejected / withdrawn.
-- ---------------------------------------------------------------------
create table if not exists applications (
    id uuid primary key default gen_random_uuid(),
    user_id uuid not null references users(id) on delete cascade,
    role_id uuid not null references roles(id) on delete cascade,
    status text not null default 'discovered'
        check (status in (
            'discovered', 'saved', 'applied', 'oa',
            'interview', 'offer', 'rejected', 'withdrawn'
        )),
    application_date date,
    deadline date,
    interview_date date,
    notes text,
    hours_available_per_day numeric(4, 2),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (user_id, role_id)
);

-- Safe to re-run against a database created from an earlier version of
-- this schema: adds application_date/deadline/notes if missing, and
-- lowercases status values (this schema previously used Title Case
-- values like 'Discovered').
alter table applications add column if not exists application_date date;
alter table applications add column if not exists deadline date;
alter table applications add column if not exists notes text;
update applications set status = lower(status) where status <> lower(status);
alter table applications alter column status set default 'discovered';
alter table applications drop constraint if exists applications_status_check;
alter table applications add constraint applications_status_check
    check (status in (
        'discovered', 'saved', 'applied', 'oa',
        'interview', 'offer', 'rejected', 'withdrawn'
    ));

-- ---------------------------------------------------------------------
-- assessment_results
-- Diagnostic/assessment attempts that can update skill confidence.
-- ---------------------------------------------------------------------
create table if not exists assessment_results (
    id uuid primary key default gen_random_uuid(),
    user_id uuid not null references users(id) on delete cascade,
    normalized_skill_name text not null,
    observed_level numeric(4, 2) not null,
    confidence_delta numeric(4, 2) not null default 0,
    source text,
    taken_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------
-- study_plans
-- One prep plan per (user, application), regenerated adaptively.
-- ---------------------------------------------------------------------
create table if not exists study_plans (
    id uuid primary key default gen_random_uuid(),
    user_id uuid not null references users(id) on delete cascade,
    application_id uuid references applications(id) on delete cascade,
    total_hours_available numeric(6, 2) not null,
    interview_date date,
    generated_at timestamptz not null default now(),
    is_current boolean not null default true
);

-- ---------------------------------------------------------------------
-- study_tasks
-- Individual allocated tasks within a study plan.
-- ---------------------------------------------------------------------
create table if not exists study_tasks (
    id uuid primary key default gen_random_uuid(),
    study_plan_id uuid not null references study_plans(id) on delete cascade,
    normalized_skill_name text not null,
    allocated_hours numeric(5, 2) not null,
    priority_score numeric(6, 3) not null,
    task_description text,
    is_complete boolean not null default false,
    created_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------
-- ingestion_runs
-- One row per ingestion+matching pipeline run, for pipeline metrics and
-- auditability. Append-only audit log, NOT an idempotent-upsert table
-- like roles/favorites/applications - every run is a genuinely new
-- event, so backend/db/metrics.py inserts a fresh row per call rather
-- than upserting against some "same run" identity (there isn't one).
-- ---------------------------------------------------------------------
create table if not exists ingestion_runs (
    id uuid primary key default gen_random_uuid(),
    started_at timestamptz not null default now(),
    finished_at timestamptz,
    source text,
    jobs_ingested integer not null default 0,
    jobs_deduplicated integer not null default 0,
    jobs_eliminated_hard_filter integer not null default 0,
    jobs_eliminated_keyword_filter integer not null default 0,
    jobs_eliminated_semantic integer not null default 0,
    jobs_reaching_llm integer not null default 0,
    estimated_llm_calls_avoided integer not null default 0,
    serial_ingestion_seconds numeric(10, 3),
    concurrent_ingestion_seconds numeric(10, 3),
    llm_prompt_tokens integer,
    llm_completion_tokens integer,
    llm_total_tokens integer,
    llm_estimated_cost_usd numeric(12, 6)
);

-- Safe to re-run against a database created from an earlier version of
-- this schema, before the keyword-filter stage (backend.matching.filters)
-- and LLM token/cost tracking (backend.utils.metrics) existed.
alter table ingestion_runs add column if not exists jobs_eliminated_keyword_filter integer not null default 0;
alter table ingestion_runs add column if not exists llm_prompt_tokens integer;
alter table ingestion_runs add column if not exists llm_completion_tokens integer;
alter table ingestion_runs add column if not exists llm_total_tokens integer;
alter table ingestion_runs add column if not exists llm_estimated_cost_usd numeric(12, 6);

-- ---------------------------------------------------------------------
-- pipeline_metrics
-- Generic timeseries of named metric values, keyed to an ingestion run.
-- ---------------------------------------------------------------------
create table if not exists pipeline_metrics (
    id uuid primary key default gen_random_uuid(),
    ingestion_run_id uuid references ingestion_runs(id) on delete cascade,
    metric_name text not null,
    metric_value numeric(14, 4) not null,
    recorded_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------
-- Helpful indexes beyond the uniqueness constraints above.
-- ---------------------------------------------------------------------
create index if not exists idx_candidate_skills_user_id on candidate_skills(user_id);
create index if not exists idx_role_requirements_role_id on role_requirements(role_id);
create index if not exists idx_fit_scores_user_id on fit_scores(user_id);
create index if not exists idx_favorites_user_id on favorites(user_id);
create index if not exists idx_applications_user_id on applications(user_id);
create index if not exists idx_applications_status on applications(status);
create index if not exists idx_study_tasks_study_plan_id on study_tasks(study_plan_id);
